#Requires AutoHotkey v2.1-alpha.30

; ScriptExporter — turns the current studio settings into a standalone .ahk that
; runs anywhere the fork (or stock alpha.30) is installed, with no #Include and
; nothing to copy beside it except a .cur when the cursor swap is switched on.
;
; The engine classes are inlined verbatim from Engine\ rather than duplicated
; here, so a fix to LoupeEngine reaches every script exported afterwards.
;
; Emitted code lines use single-quoted AHK strings: alpha.30 rejects the ""
; doubling that v2.0 accepted, and single quotes keep the generated DllCalls
; readable without a backtick on every argument.

class ScriptExporter {
    ; Where the engine sources live, resolved from this file rather than from
    ; A_ScriptDir — the entry script is not always CursorMarker.ahk.
    static EngineDir => RegExReplace(A_LineFile, "\\[^\\]+$")

    static Build(parts, engineDir := "") {
        if (engineDir = "")
            engineDir := ScriptExporter.EngineDir
        name := parts.Has("Name") ? parts["Name"] : "CursorMarker"
        wantLoupe := parts.Has("Loupe") && parts["Loupe"]
        wantHl := parts.Has("Highlight") && parts["Highlight"]
        wantCursor := parts.Has("Cursor") && parts["Cursor"]
        curFile := parts.Has("CursorFile") ? parts["CursorFile"] : ""

        if !(wantLoupe || wantHl || wantCursor)
            throw ValueError("Nothing selected to export — pick at least one component.", -1)

        out := []
        out.Push("; " name " — generated by CursorMarker on " FormatTime(A_Now, "yyyy-MM-dd HH:mm") ".")
        out.Push(";")
        out.Push("; Standalone. Drop it anywhere and run it; the engines below are inlined.")
        for line in ScriptExporter.HotkeyNotes(wantLoupe, wantHl)
            out.Push(line)
        out.Push("")
        out.Push("#Requires AutoHotkey v2.1-alpha.30")
        out.Push("#SingleInstance Force")
        out.Push("Persistent")
        out.Push("")

        if wantLoupe {
            out.Push("; Loupe settings")
            for line in ScriptExporter.LoupeSettings()
                out.Push(line)
            out.Push("")
        }
        if wantHl {
            out.Push("; Cursor highlight settings")
            for line in ScriptExporter.HighlightSettings()
                out.Push(line)
            out.Push("")
        }
        if wantCursor {
            for line in ScriptExporter.CursorBlock(curFile)
                out.Push(line)
            out.Push("")
        }

        for line in ScriptExporter.Hotkeys(wantLoupe, wantHl)
            out.Push(line)
        out.Push("")

        if wantLoupe
            out.Push(ScriptExporter.Inline(engineDir "\LoupeEngine.ahk"))
        if wantHl
            out.Push(ScriptExporter.Inline(engineDir "\HighlightEngine.ahk"))

        return Trim(ScriptExporter.Join(out), "`r`n `t") "`r`n"
    }

    static Write(path, text) {
        dir := RegExReplace(path, "\\[^\\]+$")
        if (dir != "" && !DirExist(dir))
            DirCreate(dir)
        file := FileOpen(path, "w", "UTF-8")
        if !file
            throw OSError("Could not open " path " for writing.", -1)
        try
            file.Write(text)
        finally
            file.Close()
        return path
    }

    static HotkeyNotes(wantLoupe, wantHl) {
        notes := []
        keys := []
        if wantLoupe {
            ScriptExporter.NoteKey(keys, MarkerConfig.Get("Loupe.HotToggle"), "toggle the loupe")
            ScriptExporter.NoteKey(keys, MarkerConfig.Get("Loupe.HotZoomIn"), "zoom in")
            ScriptExporter.NoteKey(keys, MarkerConfig.Get("Loupe.HotZoomOut"), "zoom out")
        }
        if (wantLoupe && MarkerConfig.Num("Loupe.WheelZoom"))
            ScriptExporter.NoteKey(keys, "Ctrl+Wheel", "zoom in and out, while the lens is up")
            ScriptExporter.NoteKey(keys, "Ctrl+Shift+Wheel", "make the lens bigger or smaller")
        if wantHl
            ScriptExporter.NoteKey(keys, MarkerConfig.Get("Hl.HotToggle"), "toggle the cursor highlight")
        if !keys.Length
            return notes
        notes.Push(";")
        notes.Push("; Hotkeys")
        for k in keys
            notes.Push("; " k)
        return notes
    }

    static NoteKey(keys, hotkey, what) {
        if (Trim(hotkey) != "")
            keys.Push(Format("{:-16}", hotkey) what)
    }

    static LoupeSettings() {
        lines := []
        lines.Push("LoupeEngine.LensSize := " MarkerConfig.Num("Loupe.LensSize"))
        lines.Push("LoupeEngine.Zoom := " Round(MarkerConfig.Num("Loupe.Zoom") / 10, 1))
        lines.Push("LoupeEngine.BorderWidth := " MarkerConfig.Num("Loupe.BorderWidth"))
        lines.Push("LoupeEngine.BorderColor := 0x" MarkerColor.ToHex(MarkerConfig.RGB("Loupe.BorderColor")))
        lines.Push("LoupeEngine.Interval := " MarkerConfig.Num("Loupe.Interval"))
        lines.Push("LoupeEngine.Shape := " ScriptExporter.Quote(MarkerConfig.Get("Loupe.Shape")))
        lines.Push("LoupeEngine.Follow := " ScriptExporter.Quote(MarkerConfig.Get("Loupe.Follow")))
        lines.Push("LoupeEngine.OffsetX := " MarkerConfig.Num("Loupe.OffsetX"))
        lines.Push("LoupeEngine.OffsetY := " MarkerConfig.Num("Loupe.OffsetY"))
        lines.Push("LoupeEngine.Corner := " ScriptExporter.Quote(MarkerConfig.Get("Loupe.Corner")))
        lines.Push("LoupeEngine.HideFromCapture := " ScriptExporter.Bool(InStr(MarkerConfig.Get("Loupe.Capture"), "Hide")))
        lines.Push("LoupeEngine.Crosshair := " ScriptExporter.Bool(MarkerConfig.Num("Loupe.Crosshair")))
        lines.Push("LoupeEngine.Smooth := " ScriptExporter.Bool(MarkerConfig.Num("Loupe.Smooth")))
        lines.Push("LoupeEngine.WheelZoom := " ScriptExporter.Bool(MarkerConfig.Num("Loupe.WheelZoom")))
        lines.Push("LoupeEngine.ZoomStep := " Round(MarkerConfig.Num("Loupe.ZoomStep") / 10, 1))
        return lines
    }

    static HighlightSettings() {
        lines := []
        lines.Push("HighlightEngine.RingRadius := " MarkerConfig.Num("Hl.RingRadius"))
        lines.Push("HighlightEngine.RingWidth := " MarkerConfig.Num("Hl.RingWidth"))
        lines.Push("HighlightEngine.RingColor := 0x" MarkerColor.ToHex(MarkerConfig.RGB("Hl.RingColor")))
        lines.Push("HighlightEngine.RingAlpha := " MarkerConfig.Num("Hl.RingAlpha"))
        lines.Push("HighlightEngine.ShowFill := " ScriptExporter.Bool(MarkerConfig.Num("Hl.Fill")))
        lines.Push("HighlightEngine.FillColor := 0x" MarkerColor.ToHex(MarkerConfig.RGB("Hl.FillColor")))
        lines.Push("HighlightEngine.FillAlpha := " MarkerConfig.Num("Hl.FillAlpha"))
        lines.Push("HighlightEngine.Ripple := " ScriptExporter.Bool(MarkerConfig.Num("Hl.Ripple")))
        lines.Push("HighlightEngine.RippleMax := " MarkerConfig.Num("Hl.RippleMax"))
        lines.Push("HighlightEngine.RippleMs := " MarkerConfig.Num("Hl.RippleMs"))
        lines.Push("HighlightEngine.ColorL := 0x" MarkerColor.ToHex(MarkerConfig.RGB("Hl.ColorL")))
        lines.Push("HighlightEngine.ColorM := 0x" MarkerColor.ToHex(MarkerConfig.RGB("Hl.ColorM")))
        lines.Push("HighlightEngine.ColorR := 0x" MarkerColor.ToHex(MarkerConfig.RGB("Hl.ColorR")))
        lines.Push("HighlightEngine.Interval := " MarkerConfig.Num("Hl.Interval"))
        lines.Push("HighlightEngine.Start()")
        return lines
    }

    ; No GDI+ at runtime: the .cur is already on disk, so the generated script
    ; only loads it, installs it, and hands the pointer back on exit.
    static CursorBlock(curFile) {
        leaf := RegExReplace(curFile, "^.*\\")
        if (leaf = "")
            leaf := "CursorMarker.cur"
        target := MarkerConfig.Get("Cur.Target")
        ids := ""
        for id in CursorPainter.TargetIds(target)
            ids .= (ids = "" ? "" : ", ") id

        lines := []
        lines.Push("; Cursor swap — " target ". The pointer is restored on exit, and")
        lines.Push("; Ctrl+Alt+F12 puts it back by hand if the script is ever killed abruptly.")
        lines.Push("MarkerCursorFile := A_ScriptDir " ScriptExporter.Quote("\" leaf))
        lines.Push("MarkerApplyCursor()")
        lines.Push("OnExit(MarkerRestoreCursor)")
        lines.Push("^!F12::MarkerRestoreCursor()")
        lines.Push("")
        lines.Push("MarkerApplyCursor() {")
        lines.Push("    global MarkerCursorFile")
        lines.Push('    source := DllCall("User32\LoadCursorFromFile", "Str", MarkerCursorFile, "Ptr")')
        lines.Push("    if !source {")
        lines.Push('        MsgBox("Could not load " MarkerCursorFile, "Cursor swap", 0x30)')
        lines.Push("        return")
        lines.Push("    }")
        lines.Push("    for id in [" ids "] {")
        lines.Push('        copy := DllCall("User32\CopyImage", "Ptr", source, "UInt", 2, "Int", 0, "Int", 0, "UInt", 0, "Ptr")')
        lines.Push("        if !copy")
        lines.Push("            continue")
        lines.Push('        if !DllCall("User32\SetSystemCursor", "Ptr", copy, "UInt", id, "Int")')
        lines.Push('            DllCall("User32\DestroyCursor", "Ptr", copy)')
        lines.Push("    }")
        lines.Push('    DllCall("User32\DestroyCursor", "Ptr", source)')
        lines.Push("}")
        lines.Push("")
        lines.Push("MarkerRestoreCursor(*) {")
        lines.Push('    DllCall("User32\SystemParametersInfoW", "UInt", 0x0057, "UInt", 0, "Ptr", 0, "UInt", 0)')
        lines.Push("    return 0")        ; OnExit reads the result; never hand it an unset
        lines.Push("}")
        return lines
    }

    static Hotkeys(wantLoupe, wantHl) {
        lines := []
        if wantLoupe {
            ScriptExporter.Emit(lines, MarkerConfig.Get("Loupe.HotToggle"), "LoupeEngine.Toggle()")
            ScriptExporter.Emit(lines, MarkerConfig.Get("Loupe.HotZoomIn"), "LoupeEngine.ZoomBy(0.5)")
            ScriptExporter.Emit(lines, MarkerConfig.Get("Loupe.HotZoomOut"), "LoupeEngine.ZoomBy(-0.5)")
        }
        if wantHl
            ScriptExporter.Emit(lines, MarkerConfig.Get("Hl.HotToggle"), "HighlightEngine.Toggle()")
        if lines.Length
            lines.InsertAt(1, "; Hotkeys")
        return lines
    }

    static Emit(lines, hotkey, body) {
        if (Trim(hotkey) != "")
            lines.Push(Trim(hotkey) "::" body)
    }

    static Inline(path) {
        if !FileExist(path)
            throw OSError("Engine file missing: " path, -1)
        if (FileGetSize(path) = 0)
            throw OSError("Engine file is empty: " path, -1)
        kept := []
        for line in StrSplit(FileRead(path, "UTF-8"), "`n", "`r") {
            if RegExMatch(line, "i)^\s*#(Requires|Include|SingleInstance)\b")
                continue
            kept.Push(line)
        }
        return Trim(ScriptExporter.Join(kept), "`r`n")
    }

    static Join(lines) {
        text := ""
        for line in lines
            text .= line "`r`n"
        return text
    }

    ; alpha.30 dropped "" doubling, so an embedded quote gets a backtick instead.
    static Quote(text) => '"' StrReplace(text, '"', '``"') '"'
    static Bool(value) => value ? "true" : "false"
}
